#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.239
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBUpdateStarter
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="suzadb")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertPriceLists(PriceLists instance);
    partial void UpdatePriceLists(PriceLists instance);
    partial void DeletePriceLists(PriceLists instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::DBUpdateStarter.Properties.Settings.Default.suzadbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PriceLists> PriceLists
		{
			get
			{
				return this.GetTable<PriceLists>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PriceLists")]
	public partial class PriceLists : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PriceListID;
		
		private string _PriceListName;
		
		private int _SupplierID;
		
		private string _PriceListFileName;
		
		private string _PriceListAltFileName;
		
		private string _PriceListExtension;
		
		private int _DaysToDelivery;
		
		private bool _Confidence;
		
		private string _MailFrom;
		
		private string _MailSubject;
		
		private System.Nullable<System.DateTime> _LastUpdate;
		
		private bool _UpdateFromMail;
		
		private string _PriceURL;
		
		private string _Login;
		
		private string _Password;
		
		private int _MaxDaysForUpdate;
		
		private string _GeneratingShedule;
		
		private int _UpdateMode;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPriceListIDChanging(int value);
    partial void OnPriceListIDChanged();
    partial void OnPriceListNameChanging(string value);
    partial void OnPriceListNameChanged();
    partial void OnSupplierIDChanging(int value);
    partial void OnSupplierIDChanged();
    partial void OnPriceListFileNameChanging(string value);
    partial void OnPriceListFileNameChanged();
    partial void OnPriceListAltFileNameChanging(string value);
    partial void OnPriceListAltFileNameChanged();
    partial void OnPriceListExtensionChanging(string value);
    partial void OnPriceListExtensionChanged();
    partial void OnDaysToDeliveryChanging(int value);
    partial void OnDaysToDeliveryChanged();
    partial void OnConfidenceChanging(bool value);
    partial void OnConfidenceChanged();
    partial void OnMailFromChanging(string value);
    partial void OnMailFromChanged();
    partial void OnMailSubjectChanging(string value);
    partial void OnMailSubjectChanged();
    partial void OnLastUpdateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastUpdateChanged();
    partial void OnUpdateFromMailChanging(bool value);
    partial void OnUpdateFromMailChanged();
    partial void OnPriceURLChanging(string value);
    partial void OnPriceURLChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnMaxDaysForUpdateChanging(int value);
    partial void OnMaxDaysForUpdateChanged();
    partial void OnGeneratingSheduleChanging(string value);
    partial void OnGeneratingSheduleChanged();
    partial void OnUpdateModeChanging(int value);
    partial void OnUpdateModeChanged();
    #endregion
		
		public PriceLists()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceListID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PriceListID
		{
			get
			{
				return this._PriceListID;
			}
			set
			{
				if ((this._PriceListID != value))
				{
					this.OnPriceListIDChanging(value);
					this.SendPropertyChanging();
					this._PriceListID = value;
					this.SendPropertyChanged("PriceListID");
					this.OnPriceListIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceListName", DbType="NVarChar(140) NOT NULL", CanBeNull=false)]
		public string PriceListName
		{
			get
			{
				return this._PriceListName;
			}
			set
			{
				if ((this._PriceListName != value))
				{
					this.OnPriceListNameChanging(value);
					this.SendPropertyChanging();
					this._PriceListName = value;
					this.SendPropertyChanged("PriceListName");
					this.OnPriceListNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierID", DbType="Int NOT NULL")]
		public int SupplierID
		{
			get
			{
				return this._SupplierID;
			}
			set
			{
				if ((this._SupplierID != value))
				{
					this.OnSupplierIDChanging(value);
					this.SendPropertyChanging();
					this._SupplierID = value;
					this.SendPropertyChanged("SupplierID");
					this.OnSupplierIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceListFileName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PriceListFileName
		{
			get
			{
				return this._PriceListFileName;
			}
			set
			{
				if ((this._PriceListFileName != value))
				{
					this.OnPriceListFileNameChanging(value);
					this.SendPropertyChanging();
					this._PriceListFileName = value;
					this.SendPropertyChanged("PriceListFileName");
					this.OnPriceListFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceListAltFileName", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string PriceListAltFileName
		{
			get
			{
				return this._PriceListAltFileName;
			}
			set
			{
				if ((this._PriceListAltFileName != value))
				{
					this.OnPriceListAltFileNameChanging(value);
					this.SendPropertyChanging();
					this._PriceListAltFileName = value;
					this.SendPropertyChanged("PriceListAltFileName");
					this.OnPriceListAltFileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceListExtension", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string PriceListExtension
		{
			get
			{
				return this._PriceListExtension;
			}
			set
			{
				if ((this._PriceListExtension != value))
				{
					this.OnPriceListExtensionChanging(value);
					this.SendPropertyChanging();
					this._PriceListExtension = value;
					this.SendPropertyChanged("PriceListExtension");
					this.OnPriceListExtensionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaysToDelivery", DbType="Int NOT NULL")]
		public int DaysToDelivery
		{
			get
			{
				return this._DaysToDelivery;
			}
			set
			{
				if ((this._DaysToDelivery != value))
				{
					this.OnDaysToDeliveryChanging(value);
					this.SendPropertyChanging();
					this._DaysToDelivery = value;
					this.SendPropertyChanged("DaysToDelivery");
					this.OnDaysToDeliveryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Confidence", DbType="Bit NOT NULL")]
		public bool Confidence
		{
			get
			{
				return this._Confidence;
			}
			set
			{
				if ((this._Confidence != value))
				{
					this.OnConfidenceChanging(value);
					this.SendPropertyChanging();
					this._Confidence = value;
					this.SendPropertyChanged("Confidence");
					this.OnConfidenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailFrom", DbType="NVarChar(255)")]
		public string MailFrom
		{
			get
			{
				return this._MailFrom;
			}
			set
			{
				if ((this._MailFrom != value))
				{
					this.OnMailFromChanging(value);
					this.SendPropertyChanging();
					this._MailFrom = value;
					this.SendPropertyChanged("MailFrom");
					this.OnMailFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailSubject", DbType="NVarChar(500)")]
		public string MailSubject
		{
			get
			{
				return this._MailSubject;
			}
			set
			{
				if ((this._MailSubject != value))
				{
					this.OnMailSubjectChanging(value);
					this.SendPropertyChanging();
					this._MailSubject = value;
					this.SendPropertyChanged("MailSubject");
					this.OnMailSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastUpdate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastUpdate
		{
			get
			{
				return this._LastUpdate;
			}
			set
			{
				if ((this._LastUpdate != value))
				{
					this.OnLastUpdateChanging(value);
					this.SendPropertyChanging();
					this._LastUpdate = value;
					this.SendPropertyChanged("LastUpdate");
					this.OnLastUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateFromMail", DbType="Bit NOT NULL")]
		public bool UpdateFromMail
		{
			get
			{
				return this._UpdateFromMail;
			}
			set
			{
				if ((this._UpdateFromMail != value))
				{
					this.OnUpdateFromMailChanging(value);
					this.SendPropertyChanging();
					this._UpdateFromMail = value;
					this.SendPropertyChanged("UpdateFromMail");
					this.OnUpdateFromMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceURL", DbType="NVarChar(255)")]
		public string PriceURL
		{
			get
			{
				return this._PriceURL;
			}
			set
			{
				if ((this._PriceURL != value))
				{
					this.OnPriceURLChanging(value);
					this.SendPropertyChanging();
					this._PriceURL = value;
					this.SendPropertyChanged("PriceURL");
					this.OnPriceURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="NVarChar(50)")]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDaysForUpdate", DbType="Int NOT NULL")]
		public int MaxDaysForUpdate
		{
			get
			{
				return this._MaxDaysForUpdate;
			}
			set
			{
				if ((this._MaxDaysForUpdate != value))
				{
					this.OnMaxDaysForUpdateChanging(value);
					this.SendPropertyChanging();
					this._MaxDaysForUpdate = value;
					this.SendPropertyChanged("MaxDaysForUpdate");
					this.OnMaxDaysForUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GeneratingShedule", DbType="NVarChar(50)")]
		public string GeneratingShedule
		{
			get
			{
				return this._GeneratingShedule;
			}
			set
			{
				if ((this._GeneratingShedule != value))
				{
					this.OnGeneratingSheduleChanging(value);
					this.SendPropertyChanging();
					this._GeneratingShedule = value;
					this.SendPropertyChanged("GeneratingShedule");
					this.OnGeneratingSheduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateMode", DbType="Int NOT NULL")]
		public int UpdateMode
		{
			get
			{
				return this._UpdateMode;
			}
			set
			{
				if ((this._UpdateMode != value))
				{
					this.OnUpdateModeChanging(value);
					this.SendPropertyChanging();
					this._UpdateMode = value;
					this.SendPropertyChanged("UpdateMode");
					this.OnUpdateModeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
